version: '3.8'

services:
  nps_latam_system:
    build: .
    container_name: nps_latam_monolith
    ports:
      - "8000:8000" # API
      - "8501:8501" # Streamlit
      - "5001:5000" # MLflow (Mapped to 5001 to avoid AirPlay/System conflicts)
    env_file:
      - .env
    environment:
      - API_URL=http://localhost:8000
    volumes:
      - ./Data:/app/Data
      - ./mlruns:/app/mlruns
    networks:
      - nps_net

networks:
  nps_net:
    driver: bridge
